# Generated by Django 6.1 on 2026-08-09 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cuil', models.CharField(max_length=13, unique=True)),
                ('categoria_suterh', models.CharField(max_length=50)),
                ('sueldo_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargados', to='core.consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_gasto', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('EXTRAORDINARIO', 'Extraordinario'), ('RESERVA', 'Fondo de Reserva')], max_length=20)),
                ('archivo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.consorcio')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='core.periodo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='proveedores.proveedor')),
            ],
        ),
    ]
