# Generated by Django 6.1 on 2026-08-09 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranzas', '0001_initial'),
        ('core', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ordinario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_extraordinario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_fondo_reserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada')], default='BORRADOR', max_length=15)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='liquidaciones', to='core.consorcio')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='liquidaciones', to='core.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDetalleUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_ordinario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_extraordinario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_fondo_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='liquidaciones.liquidacion')),
                ('unidad_funcional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='liquidaciones_uf', to='cobranzas.unidadfuncional')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aportes_retenciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f931_generado', models.BooleanField(default=False)),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='liquidaciones_sueldo', to='proveedores.encargado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='liquidaciones_sueldo', to='core.periodo')),
            ],
        ),
    ]
