# Generated by Django 6.1 on 2026-08-09 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_uf', models.CharField(max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('coeficiente', models.DecimalField(decimal_places=4, max_digits=5)),
                ('codigo_referencia', models.CharField(blank=True, max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_funcionales', to='core.consorcio')),
                ('propietario', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PROP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('TOTAL', 'Total'), ('PARCIAL', 'Parcial')], max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('id_transaccion_pasarela', models.CharField(max_length=100, unique=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='core.periodo')),
                ('unidad_funcional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='cobranzas.unidadfuncional')),
            ],
        ),
    ]
