# Generated by Django 6.1 on 2026-08-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranzas', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='portal.notificacion')),
                ('propietario', models.ForeignKey(limit_choices_to={'rol': 'PROP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_cierre', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='core.consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='portal.votacion')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='portal.opcionvotacion')),
                ('unidad_funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='cobranzas.unidadfuncional')),
            ],
            options={
                'unique_together': {('opcion', 'unidad_funcional')},
            },
        ),
    ]
